I'm dumb
SheepTester/primitive-cloud-server pull request #24
Opened 2024-12-18 18:31 UTC by KianiDev

Incorrect tasks.json for Codesandbox. I'm blind and somehow didn't see that the program wasn't running. Sorry

2024-12-18 18:32 UTC, KianiDev commented
The user just needs to type in `npm start` and the server is gonna start.

2024-12-20 08:07 UTC, SheepTester requested changes

2024-12-20 08:07 UTC, SheepTester commented on .codesandbox/tasks.json
> +        "command": "npm install" // I'm dumb, I know
dont need the comment in the file haha, it'll be confusing to see in the future

```suggestion
        "command": "npm install"
```

2025-01-01 16:35 UTC, KianiDev commented
I'll fix it as soon as I can

2025-01-02 10:15 UTC, KianiDev commented
Ok. Fixed

2025-01-02 19:07 UTC, merged